title: Nickey Docs
description: Nickeyシリーズのビルド・セットアップガイド
image: /assets/images/nickey-hero.jpg
lang: ja
url: https://nixiy.github.io
baseurl: /nickey-docs

theme: minima
markdown: kramdown
kramdown:
  input: GFM

repository: nixiy/nickey-docs

header_pages:
  - nickey44/index.md
  - nickey44a/index.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - serve.ps1
  - vendor
